// tell me a joke 
const RandomJokeGenerator=()=>{
    let RandomOption=[
        `Why don't scientists trust atoms? Because they make up everything.`,
        `Why don't eggs tell jokes? They'd crack each other up.`,
        `Why did the tomato turn red? Because it saw the salad dressing!`,
        `What do you call a fake noodle? An impasta.`,
        `Why did the scarecrow win an award? Because he was outstanding in his field.`,
        `Why don't lobsters share? Because they're shellfish.`,
        `What do you call a group of cows playing instruments? A moo-sical band.`,
        `Why did the bicycle fall over? Because it was two-tired.`,
        `Why did the chicken cross the playground? To get to the other slide.`,
        `What do you call a bear with no socks on? Barefoot.`,
        `Why did the banana go to the doctor? He wasn't peeling well.`,
        `Why did the astronaut break up with his girlfriend? Because he needed space.`,
        `Why did the mushroom go to the party? Because he was a fun-gi.`,
        `Why did the pencil break up with the eraser? It was a sharp move.`,
        `What do you call a can opener that doesn't work? A can't opener.`,
        `Why did the baker go to the bank? He needed dough.`,
        `Why did the turkey join the band? He was a drumstick.`,
        `Why did the computer go to the doctor? It had a virus!`,
        `What do you call a dog that does magic tricks? A labracadabrador.`,
        `Why did the kid bring a ladder to school? He wanted to reach his full potential.`,
        `Why did the rabbit go to the doctor? He had hare-loss.`,
        `Why did the orange stop in the middle of the road? Because it ran out of juice.`,
        `Why did the computer screen go to therapy? It was feeling a little glitchy.`,
        `Why did the kid bring a magnet to school? He wanted to attract attention.`,
        `Why did the lemon quit his job? Because it was feeling sour.`,
        `Why did the rabbit get kicked out of the bar? Because he was making too many hare-brained jokes.`,
        `Why did the computer go on a diet? To lose some bytes.`,
        `Why did the banana go to the hair salon? Because he wasn't peeling well.`,
        `Why did the astronaut take his pillow to the moon? So he could have a galaxy of comfort.`,
        `Why did the mushroom get invited to all the parties? Because he's a fun-gi.`,
        `Why did the pencil go to the party? Because it was a sharp dresser.`,
        `Why did the scarecrow win a prize? Because he was outstanding in his field.`,
        `Why did the computer go to the doctor? It had a little glitch.`,
        `Why did the kid bring a compass to school? He wanted to navigate his way to success.`,
        `Why did the cat join a band? Because it wanted to be the purr-cussionist.`,
        `Why did the dog go to the vet? Because it was feeling ruff.`,
        `Why did the elephant quit the circus? Because it was tired of working for peanuts.`,
        `Why did the math book look so sad? Because it had too many problems.`,
        `Why did the student bring a ladder to school? He wanted to reach the high scores.`,
        `What do you call a group of chickens playing instruments? A fowl orchestra.`,
        `Why did the rabbit go to the gym? To get some paws-itive reinforcement.`,
        `Why did the computer screen go to the doctor? It had a pixel-ated vision.`,
        `Why did the kid bring a flashlight to school? He wanted to brighten up his day.`,
        `What do you call a can of soda that's sad? A de-pressurized can.`,
        `Why did the banana split? Because it wasn't peeling well under the pressure.`,
        `Why did the astronaut break up with his girlfriend? Because he needed space to reflect.`,
        `Why did the computer go to therapy? It had a little glitch in its system.`,
        `Why did the kid bring a book to school? He wanted to get a novel idea.`,
        `What do you call a group of cows playing instruments? A moo-sical band with a beefed-up sound.`,
        `Why did the rabbit go to the beauty parlor? To get a hare-do.`,
        `Why did the computer screen go to the gym? To get some pixel-fect abs.`,
        `Why did the kid bring a magnet to school? He wanted to attract some attention from the teacher.`,
        `Why did the coffee file a police report? It got mugged.`,
        `Why did the bicycle fall over? Because it was two-tired.`,
        `What do you call a group of cats playing instruments? A mew-sical band.`,
        `Why did the baker go to the bank? He needed dough.`,
        `Why did the mushroom get invited to all the parties? Because he's a fun-gi.`,
        `Why did the pencil break up with the eraser? It was a sharp move.`,
        `What do you call a can opener that doesn't work? A can't opener.`,
        `Why did the turkey join the band? He was a drumstick.`,
        `Why did the computer go to the doctor? It had a virus!`,
        `What do you call a dog that does magic tricks? A labracadabrador.`,
        `Why did the kid bring a ladder to school? He wanted to reach his full potential.`,
        `Why did the rabbit go to the doctor? He had hare-loss.`,
        `Why did the orange stop in the middle of the road? Because it ran out of juice.`,
        `Why did the computer screen go to therapy? It was feeling a little glitchy.`,
        `Why did the kid bring a magnet to school? He wanted to attract attention.`,
        `Why did the lemon quit his job? Because it was feeling sour.`,
        `Why did the rabbit get kicked out of the bar? Because he was making too many hare-brained jokes.`,
        `Why did the computer go on a diet? To lose some bytes.`,
        `Why did the banana go to the hair salon? Because he wasn't peeling well.`,
        `Why did the astronaut take his pillow to the moon? So he could have a galaxy of comfort.`,
        `Why did the mushroom get invited to all the parties? Because he's a fun-gi.`,
        `Why did the pencil go to the party? Because it was a sharp dresser.`,
        `Why did the scarecrow win a prize? Because he was outstanding in his field.`,
        `Why did the computer go to the doctor? It had a little glitch.`,
        `Why did the kid bring a compass to school? He wanted to navigate his way to success.`,
        `Why did the cat join a band? Because it wanted to be the purr-cussionist.`,
        `Why did the dog go to the vet? Because it was feeling ruff.`,
        `Why did the elephant quit the circus? Because it was tired of working for peanuts.`,
        `Why did the math book look so sad? Because it had too many problems.`,
        `Why did the student bring a ladder to school? He wanted to reach the high scores.`,
        `What do you call a group of chickens playing instruments? A fowl orchestra.`,
        `Why did the rabbit go to the gym? To get some paws-itive reinforcement.`,
        `Why did the computer screen go to the doctor? It had a pixel-ated vision.`,
        `Why did the kid bring a flashlight to school? He wanted to brighten up his day.`,
        `What do you call a can of soda that's sad? A de-pressurized can.`,
        `Why did the banana split? Because it wasn't peeling well under the pressure.`,
        `Why did the astronaut break up with his girlfriend? Because he needed space to reflect.`,
        `Why did the computer go to therapy? It had a little glitch in its system.`,
        `Why did the kid bring a book to school? He wanted to get a novel idea.`,
        `What do you call a group of cows playing instruments? A moo-sical band with a beefed-up sound.`,
        `Why did the rabbit go to the beauty parlor? To get a hare-do.`,
        `Why did the computer screen go to the gym? To get some pixel-fect abs.`,
        `Why did the kid bring a magnet to school? He wanted to attract some attention from the teacher.`,
        `Why did the chicken cross the playground? To get to the other slide.`,
        `Why did the banana go to the doctor? He wasn't peeling well.`,
        `Why did the astronaut break up with his girlfriend? Because he needed space.`,
        `Why did the mushroom go to the party? Because he was a fun-gi.`,
        `Why did the pencil break up with the eraser? It was a sharp move.`,
        `What do you call a can opener that doesn't work? A can't opener.`,
        `Why did the baker go to the bank? He needed dough.`,
        `Why did the turkey join the band? He was a drumstick.`,
        `Why did the computer go to the doctor? It had a virus!`,
        `What do you call a dog that does magic tricks? A labracadabrador.`]
    
    let RandomIndex=Math.floor(Math.random()*RandomOption.length);
    let RandomJoke= RandomOption[RandomIndex];
    return RandomJoke
    }
    
    console.log(RandomJokeGenerator());
    b=document.getElementsByClassName("joke")[0];
    c=RandomJokeGenerator();
    b.innerHTML=(`${c}`);
    
    
    